name: Shanghai Ruby User Group
markdown: redcarpet
pygments: true
timezone: Asia/Shanghai
keep_files:  ['.git']
site: "http://shruby.org"
url: "http://shruby.org"
description: 'Web site of ShRuby.github.io'
exclude: ["vendor"]

save: true
lsi: false
pygments: true
